InseeFrLab/utilitR

01_R_Insee/Fiche_utiliser_utilitR.Rmd

2e PR suite à migration github

Fiche "Comment utiliser cette documentation" (suite)

---

02_Bonnes_pratiques/05-regles.Rmd

Un exemple de modification d'une fiche via l'interface Github

Correction marginale d'une typo

---

_bookdown.yml

Passage du guide des bonnes pratiques à la fin

---

.github/workflows/bookdown.yaml
.github/workflows/bookdown_prod.yaml
README.md

Pour être cohérent avec le nouveau contributing (#109 et #195), il faut ajouter la prévisualisation du site

Prévisualisation du site pour les pull requests

---

DESCRIPTION
css/style.css
index.Rmd

Mieux créditer les contributeurs, et n'utiliser que le fichier DESCRIPTION

Boite contributeurs

---

01_R_Insee/Fiche-personnaliser-R.Rmd
01_R_Insee/Fiche_installer_packages.Rmd
01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
01_R_Insee/Fiche_utiliser_ressources.Rmd
01_R_Insee/Fiche_utiliser_utilitR.Rmd
03_Fiches_thematiques/Fiche_analyse_de_donnees.Rmd
03_Fiches_thematiques/Fiche_comment_choisir_un_package.Rmd
03_Fiches_thematiques/Fiche_connexion_bdd.Rmd
03_Fiches_thematiques/Fiche_datatable.Rmd
03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd
03_Fiches_thematiques/Fiche_donnees_textuelles.Rmd
03_Fiches_thematiques/Fiche_graphiques.Rmd
03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd
03_Fiches_thematiques/Fiche_import_tables_sas.Rmd
03_Fiches_thematiques/Fiche_import_tableurs.Rmd
03_Fiches_thematiques/Fiche_joindre_donnees.Rmd
03_Fiches_thematiques/Fiche_rmarkdown.Rmd

Retire le suffixe `data-latex` dans les box, devenu inutile avec le passage à bookdown

bye bye data-latex inutile

---

01_R_Insee/Fiche-personnaliser-R.Rmd

(la PR pour laquelle j'ai oublié de créer une branche sur mon fork)

fiche personnaliser : boite insee

---

.github/workflows/automatic-test-template.yaml

Fonctionnalité exploratoire mais qu'il est nécessaire d'intégrer dans `master`

repository_dispatch pour lier GHA de la doc et du template

---

.github/workflows/bookdown-test.yaml

Extraction du nom de la branche et passage en préfixe de l'url

Un URL simplifié pour le preview

---

01_R_Insee/Fiche-personnaliser-R.Rmd
01_R_Insee/Fiche_installer_packages.Rmd
01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
01_R_Insee/Fiche_utiliser_ressources.Rmd
01_R_Insee/Fiche_utiliser_utilitR.Rmd
03_Fiches_thematiques/Fiche_analyse_de_donnees.Rmd
03_Fiches_thematiques/Fiche_connexion_bdd.Rmd
03_Fiches_thematiques/Fiche_datatable.Rmd
03_Fiches_thematiques/Fiche_donnees_textuelles.Rmd
03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd
03_Fiches_thematiques/Fiche_import_tables_sas.Rmd
03_Fiches_thematiques/Fiche_import_tableurs.Rmd
03_Fiches_thematiques/Fiche_joindre_donnees.Rmd
03_Fiches_thematiques/Fiche_survey.Rmd
03_Fiches_thematiques/Fiche_tidyverse.Rmd

Raccourcir quelques url

---

01_R_Insee/01-intro.Rmd
01_R_Insee/Fiche_utiliser_ressources.Rmd
03_Fiches_thematiques/3-Intro_partie_fiche_thematiques.Rmd
03_Fiches_thematiques/Fiche_rmarkdown.Rmd
03_Fiches_thematiques/Intro_partie_importer_donnees.Rmd
03_Fiches_thematiques/Intro_partie_manipuler_donnees.Rmd
03_Fiches_thematiques/Intro_partie_mener_un_projet_statistique.Rmd
03_Fiches_thematiques/Intro_partie_produire_sorties.Rmd
03_Fiches_thematiques/Intro_partie_utiliser_R_Insee.Rmd
_bookdown.yml

Appliquer l'ordre des fiches proposer dans #97. A ce stade, je ne déplace pas les fichiers Rmd, car cela créerait probablement des problèmes dans les autres _pull requests_. Une fois que la rédaction des contenus sera achevée, on réorganisera les dossiers contenant les Rmd.

Ordre fiches

---

DESCRIPTION

Préciser la version de pagedown

---

03_Fiches_thematiques/Fiche_donnees_textuelles.Rmd

Relecture fiche donnees textuelles

---

03_Fiches_thematiques/Fiche_datatable.Rmd
DESCRIPTION

Contributeurs

---

01_R_Insee/Fiche_installer_packages.Rmd
03_Fiches_thematiques/Fiche_datatable.Rmd

Relecture fiche packages

---

03_Fiches_thematiques/Fiche_comment_choisir_un_package.Rmd

isole parties relatives au CoPs

---

DESCRIPTION

J'ai ajouté un tag sur le repo de `doremifasolData` pour mieux identifier les versions.

tag pour figer doremifasolData

---

01_R_Insee/Fiche-personnaliser-R.Rmd

Comme promis, une relecture de la fiche écrite par @acazaubiel.

relecture fiche personnaliser R

---

03_Fiches_thematiques/Fiche_rmarkdown_param_report.Rmd

relecture fiche rapports automatisés (PY)

---

03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd
DESCRIPTION

J'ai pas tenté la compilation de documentation mais j'ai trop de dépendances manquantes.
Bonne journée à tous

Relecture fiche donnees spatiales

---

01_R_Insee/Fiche_installer_packages.Rmd

(dossier d'installation des packages sur AUS)

ajoute boîte spécificité

---

01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
03_Fiches_thematiques/Fiche_datatable.Rmd
03_Fiches_thematiques/Fiche_graphiques.Rmd
03_Fiches_thematiques/Fiche_joindre_donnees.Rmd
03_Fiches_thematiques/Fiche_rmarkdown.Rmd
03_Fiches_thematiques/Fiche_tidyverse.Rmd

ortho: consultez dans encart remarques doremifasolData

---

01_R_Insee/Fiche-personnaliser-R.Rmd

**Relecture de la fiche par Géraldine Rochambeau**
Une proposition de reformulation transmise par Géraldine sur cette fiche.

Relecture de la fiche "Personnaliser la configuration de R"

---

03_Fiches_thematiques/Fiche_joindre_donnees.Rmd

J'ai supprimé le **s** à _jointure_  car la fiche mixait les deux orthographes avec ou sans "s"

Relecture fiche joindre donnees

---

03_Fiches_thematiques/Fiche_connexion_bdd.Rmd

- [  ] Les exemples de code `R` ont été testés sur ma machine
Le chapitre est plutôt pédagogique puisqu'il expose les concepts et revient dessus de manière progressive. Il reste malgré tout assez théorique, et même si c'est pas forcément évident, peut-être serait-il intéressant de proposer un exemple reproductible avec `sqlite`  ? ( dans la même lignée que celui présent dans l'un des pages de `pour en savoir plus` : [ici](https://db.rstudio.com/dbi/) )

Relecture fiche connexion bdd

---

01_R_Insee/Fiche_installer_packages.Rmd

Voici la relecture de @ViolainePoirot sur cette fiche : 2 typos

Relecture fiche installer_packages

---

03_Fiches_thematiques/Fiche_tidyverse.Rmd

dplyr a pas mal évolué depuis R3.3.
Dans le chapitre data.table dans la partie sur les fonctions :
modif_var <- function(data, nom_variable){
data %>% 
mutate(nouveau_nom = .....)
}
Ce n'est plus nécessaire. On peut maintenant mettre un nom en "dur" dans un mutate, summarise, select, etc.
```markdown
`close #XX`
```

Ajout rename_with, across, qqs remarques, coquille

---

03_Fiches_thematiques/Fiche_se_documenter.Rmd

Une relecture rapide de la fiche (principalement des améliorations de forme).

améliorations fiche "se documenter"

---

03_Fiches_thematiques/Fiche_joindre_donnees.Rmd

Merci à @ViolainePoirot pour sa relecture et à @RLesur pour le retour. 
close #312

Relecture fiche jointures

---

03_Fiches_thematiques/Fiche_tidyverse.Rmd

Ajout section programmer tidyverse (modifs @acazaubiel dans #232)

---

03_Fiches_thematiques/Fiche_configurer_git.Rmd

git config --global http.sslVerify

---

01_R_Insee/Fiche_installer_packages.Rmd

corrige with_def

---

03_Fiches_thematiques/Fiche_import_tableurs.Rmd

Coquilles Fiche_import_tableurs.R

---

03_Fiches_thematiques/Fiche_api.Rmd

fiche api : améliorations doremifasol

---

01_R_Insee/Fiche_installer_packages.Rmd

- [] J'ai testé, sur ma machine, que la documentation compile avec mes ajouts (`bookdown::render_book("index.Rmd", output_dir = "_public", output_format = "utilitr::bs4_utilitr")` produit un résultat

ajoute référence fiche gestion dépendances

---

03_Fiches_thematiques/Fiche_datatable.Rmd

Définir le nombre de lignes imprimées

---

03_Fiches_thematiques/Fiche_configurer_git.Rmd
03_Fiches_thematiques/Fiche_connexion_bdd.Rmd
03_Fiches_thematiques/Fiche_datatable.Rmd
03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd
03_Fiches_thematiques/Fiche_donnees_textuelles.Rmd
03_Fiches_thematiques/Fiche_gerer_dependances.Rmd
03_Fiches_thematiques/Fiche_git_utilisation.Rmd
03_Fiches_thematiques/Fiche_graphiques.Rmd
03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd
03_Fiches_thematiques/Fiche_import_tables_sas.Rmd
03_Fiches_thematiques/Fiche_import_tableurs.Rmd
03_Fiches_thematiques/Fiche_resoudre_un_probleme.Rmd
03_Fiches_thematiques/Fiche_rmarkdown.Rmd
03_Fiches_thematiques/Fiche_rmarkdown_param_report.Rmd
03_Fiches_thematiques/Fiche_se_documenter.Rmd
03_Fiches_thematiques/Fiche_survey.Rmd
03_Fiches_thematiques/Fiche_tidyverse.Rmd

Enlever les éléments repris des supports de Julien Barnier. 
Uniformiser le titre des parties ressources.

Reecriture partielle

---

01_R_Insee/Fiche_installer_packages.Rmd

Enlève un peu de texte en gras.

dégraisse fiche utiliser packages

---

resources/init_9juin.sh

corrige coquille nom script

---

03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd

j'ai l'impression d'être le premier à tester cette fiche...

corrige erreur col_types

---

03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd

Remove warning readr

---

03_Fiches_thematiques/Fiche_datatable.Rmd

erreur dans le code de 20.4.3

---

03_Fiches_thematiques/Fiche_datatable.Rmd

Inversion d'un ~ et d'un ==

---

03_Fiches_thematiques/Fiche_joindre_donnees.Rmd

Typo- fiche "joindre des tables"

---

03_Fiches_thematiques/Fiche_rmarkdown.Rmd

Pour info, pas réussi à compiler sur SSPCloud
```
Output created: /home/rstudio/utilitr/_pagedown_output/rmarkdown.html
Warning message:
In xfun::prose_index(x) : Code fences are not balanced
```

affiche code

---

03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd

Typo - fiche données spatiales

---

03_Fiches_thematiques/Fiche_donnees_textuelles.Rmd

Typo - données textuelles

---

03_Fiches_thematiques/Fiche_graphiques.Rmd

Typo - ggplot2

---

03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd

Ajout d'un conseil avec un renvoi vers une fonction déjà prête sur le site de l'Insee permettant de réaliser une jointure spatiale entre un zonage à façon et une grille.
```markdown
`close #XX`
```

Ajout conseil sur zonage à façon

---

03_Fiches_thematiques/Fiche_import_tables_sas.Rmd

Mise à jour du texte sur les tables BINARY

---

03_Fiches_thematiques/Fiche_rprojects.Rmd

après ajout proxy dans .Renviron

ajoute consigne redémarrage

---

03_Fiches_thematiques/Fiche_graphiques.Rmd

voir si on peut mettre plutôt un lien relatif (je ne savais pas comment faire)

corrige lien vers présentation addins

---

.github/workflows/bookdown-test.yaml
.github/workflows/prod.yaml
03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd
CONTRIBUTING.md
DESCRIPTION
Dockerfile
README.md
_bookdown.yml

update sf pour voir si ça marche

Patch pour résoudre problème fiche carto

---

.github/workflows/automatic-test-template.yaml
.github/workflows/bookdown-test.yaml
.github/workflows/capital.yaml
.github/workflows/pagedown-test.yaml
.github/workflows/prod.yaml

Tout est dans le titre.
Je vous laisse vérifier que cela fonctionne comme prévu. Je ne voudrais pas casser des choses.
Normalement cela devrait permettre que le CI fonctionne pour les contributeurs.

remplace PAT par GITHUB_TOKEN

---

03_Fiches_thematiques/Fiche_targets.Rmd
_bookdown.yml

- un template de fiche targets pour démarrer
- Une ébauche de plan
- Description de l'intérêt de tar_make
- Notion de branches + Rmd
- intro normalisée
- librairie -> package
- ajoute slug
- améliore formulation
- typo :: qqs corrections
- typo: corrections faute
- typo : backquote au lieu de doublequote

Relecture fiche targets

---

03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd

Mise à jour de quelques liens et ajout d'un paragraphe sur le package COGugaison.
#410

Ajout COGugaison dans Fiche

---

CONTRIBUTING.md

une proposition d'ajout suite à mon expérience de (nouvel) utilisateur des forks

Ajout paragraphe création auto d'un fork

---

03_Fiches_thematiques/Fiche_targets.Rmd

Ajout lien video targets par Will Landau

---

03_Fiches_thematiques/Fiche_configurer_git.Rmd

Vers la fin de la fiche il y a un renvoi vers la fiche 8 qui contient une coquille.
```markdown
`close #XX`
```

typo - Correction coquille

---

03_Fiches_thematiques/Fiche_api.Rmd

Correction de typo
```markdown
`close #XX`
```

Correction typo Fiche_api.Rmd

---

.github/workflows/prod.yaml
CONTRIBUTING.md
Dockerfile
README.md
init_utilitr.sh

Adresse l'issue #438 et met à jour l'image docker, les liens de lancement dans CONTRIBUTING et README.
- [X ] J'ai lu le [guide des contributeurs](CONTRIBUTING.md)
- [X ] Ma proposition respecte les canons formels de la documentation `utilitR`
- [X ] Les exemples de code `R` ont été testés sur ma machine
- [X ] J'ai testé, sur ma machine, que la documentation compile avec mes ajouts (`bookdown::render_book("index.Rmd", output_dir = "_public", output_format = "utilitr::bs4_utilitr")`

Onyxia image

---

03_Fiches_thematiques/Fiche_se_documenter.Rmd

Les accolades ne sont plus nécessaires

Retire les accolades

---

03_Fiches_thematiques/Fiche_datatable.Rmd

```data.table::fcase``` utilise une implémentation plus efficace que le chainage manuel et est particulièrement intuitive dans son utilisation

ajout de la fonction ```data.table::fcase```

---

03_Fiches_thematiques/Fiche_api.qmd
03_Fiches_thematiques/Fiche_donnees_textuelles.qmd
03_Fiches_thematiques/Fiche_import_tableurs.qmd
03_Fiches_thematiques/Fiche_rmarkdown_param_report.qmd
03_Fiches_thematiques/Fiche_tidyverse.qmd

- Corrige le titre de la fiche 24 (cf. remarque de @py-b dans #467)  
- Et corrige quelques liens vers des images qui ne fonctionnent plus (+ quelques indentations de chunks)

Quelques corrections supplémentaires en lien avec #467

---

03_Fiches_thematiques/Fiche_import_fichiers_parquet.qmd

Merci pour tes modifications et ajouts @oliviermeslin, cela rend la fiche plus claire et complète 👍 
Quelques corrections mineures

Corrections mineures

---

03_Fiches_thematiques/Fiche_configurer_git.qmd

Correction de la commande git credential

---

03_Fiches_thematiques/Fiche_configurer_git.qmd

Correction du lien vers la création de jetons d'accès (site happygitwithr)

---

.github/workflows/bookdown-test.yaml
01_R_Insee/Fiche-personnaliser-R.qmd
01_R_Insee/Fiche_installer_packages.qmd
01_R_Insee/Fiche_utiliser_Rstudio_AUSv3.qmd
01_R_Insee/Fiche_utiliser_ressources.qmd
01_R_Insee/Fiche_utiliser_utilitR.qmd
03_Fiches_thematiques/Fiche_api.qmd
03_Fiches_thematiques/Fiche_configurer_git.qmd
03_Fiches_thematiques/Fiche_donnees_spatiales.qmd
03_Fiches_thematiques/Fiche_gerer_dependances.qmd
03_Fiches_thematiques/Fiche_git_utilisation.qmd
03_Fiches_thematiques/Fiche_rprojects.qmd
03_Fiches_thematiques/Fiche_se_documenter.qmd
css/box.scss
css/style-utilitr.css

Remplace Specificite par Insee dans les box

---

index.qmd

- Proposition suite à #485 
- close #485

Mention de la licence

---

02_Bonnes_pratiques/01-qualite-code.qmd

Update 01-qualite-code.qmd : typo

---

DESCRIPTION

update DESCRIPTION with dependencies

---

02_Bonnes_pratiques/02-structure-code.qmd
03_Fiches_thematiques/Fiche_api.qmd
_quarto.yml

Corrige le problème d'encadré [ici](https://book.utilitr.org/02_Bonnes_pratiques/02-structure-code.html)
Prettify le json dans la fiche API

Petites corrections

---

03_Fiches_thematiques/Fiche_git_utilisation.qmd

Hello,
Une proposition d'ajout de la formation à Git (avec RStudio) et Gitlab que nous dispensons depuis quelques semaines au SSM Agriculture.
J'en profite pour vous annoncer l'ouverture de [notre nouvelle organisation SSM Agriculture](https://github.com/SSM-Agriculture) sur github qui a vocation à s'enrichir petit à petit avec des travaux open source.

Formation ssm

---

03_Fiches_thematiques/Fiche_import_fichiers_parquet.qmd

* corrige la fonction mean_row_group_size pour prendre en compte les datasets
* corrige un nom de fonction incorrect
fixes #536

fix: coquille + généralisation d'une fonction aux datasets
