.github/workflows/bookdown_pdf_test.yaml

Comme il est souvent nécessaire de tester la compilation PDF avant de merger, cette PR propose de déclencher une action à chaque PR

Possibilité tester compilation PDF hors de master

---

01_R_Insee/Fiche_utiliser_utilitR.Rmd
css/default-fonts.css
index.Rmd

L'introduction et le chapitre 1 comprenaient beaucoup de paragraphes dupliqués. J'ai recentré l'introduction sur la présentation du projet, et la première fiche sur l'utilisation de la documentation. Pas sûr que tout soit cohérent.

Remaniement introduction

---

03_Fiches_thematiques/Fiche_donnees_spatiales.Rmd

Pour empêcher l'apparition au début du document de :
```
```

option include au lieu de echo

---

Dockerfile

Pour communiquer avec le minio du SSP Cloud (je l'utilise pour des scripts d'initialisation de RStudio).

Ajout outil mc

---

03_Fiches_thematiques/Fiche_import_tables_sas.Rmd

Mini remarque pour éviter un bug car `sjlabelled` contient une fonction qui s'appelle `read_sas`...

Quelques précisions sur l'usage de haven et sjlabelled

---

Dockerfile

Réécriture du dockerfile, en abandonnant la partie double-stage build qui tel qu'est le Dockerfile actuel, ne me semble pas utile.
Ajout de l'installation de _bookdown_ depuis le dépôt Github Rstudio.

redesign dockerfile

---

01_R_Insee/Fiche_utiliser_utilitR.Rmd

La phrase supprimée sur le COPS est spécifique à l'Insee. Je trouve aussi que cette information arrive beaucoup trop tôt dans la lecture par rapport à son importance en pratique. J'ai donc opté pour une suppression pure et simple.
À discuter.

supprime mention COPS

---

.github/workflows/prod.yaml
01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.Rmd
03_Fiches_thematiques/Fiche_datatable.Rmd
03_Fiches_thematiques/Fiche_graphiques.Rmd
03_Fiches_thematiques/Fiche_import_tableurs.Rmd
03_Fiches_thematiques/Fiche_joindre_donnees.Rmd
03_Fiches_thematiques/Fiche_rmarkdown.Rmd
03_Fiches_thematiques/Fiche_tidyverse.Rmd
DESCRIPTION

Ajout de la numéro de version pour une gestion par le tag de l'image Docker, mise en cohérence avec le numéro de version de la documentation

Ajout "à la main" du numéro de version d'utilitR

---

resources/fichiers_plats/script_init_fichiers_plats.R

Ce serait plus pratique pour la démo que les fichiers soient directement à la racine de Home.
J'ai aussi ajouté une instruction pour supprimer les zip.
Pas testé sur SSPCloud (je pense que le "~" crée les fichiers au bon endroit mais pas sûr).

fichiers plats dans Home

---

03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd

Méchants warnings au chargement de readr : 
```r
library(readr)
```
Ne sachant pas exactement la cause, je propose de les cacher.

désactive warning chargement readr

---

DESCRIPTION

Pour avoir le package disponible sur l'image docker en vue de l'écriture d'une nouvelle fiche.

ajoute targets aux dépendances

---

03_Fiches_thematiques/Fiche_comment_choisir_un_package.Rmd

La fonction `is_odd()` retournait `TRUE` pour les valeurs paires et `FALSE` pour les valeurs impaires, alors que ça doit être l'inverse.

Correction coquilles dans is_odd

---

03_Fiches_thematiques/Fiche_import_tableurs.Rmd

PR pour remplacer la fonction `readODS::ods_sheets()` (dépréciée) par `readODS::list_ods_sheets()`

Remplacement fonction ods_sheets() par list_ods_sheets()

---

CONTRIBUTING.md

Le changement d'url pour lancer un service utilitr fully configured.

Changement url lancement du service utilitr dans CONTRIBUTING

---

CONTRIBUTING.md
Dockerfile
README.md

* Dockerfile: switch to onyxia-rstudio image
* change init script
* up to 0.9.0 version for Docker image
* correct init_utilitr.sh
* correction (new) init_utilitr.sh
* correction init_utilitr.sh
* Update of launching links
* update launching links
* update packages in dockerfile
* Update Dockerfile
* stop bulk update and install only new version of htmltools
* retire doremifasol
Co-authored-by: Lino Galiana <33896139+linogaliana@users.noreply.github.com>
```markdown
`close #XX`
```
En …

Correction on docker image (#441)

---

03_Fiches_thematiques/Fiche_gerer_dependances.Rmd

En attendant + de détails sur les spécificités du comportement de {renv} sous AUS, une suggestion de modification de l'encadré.
close #443

Proposition modification encadré

---

03_Fiches_thematiques/Fiche_import_tableurs.Rmd

Contenu de la PR :  
- Suppression de la recommandation de privilégier openxlsx::read.xlsx par rapport à readxl::read_excel pour la lecture ;
- Ajout d'un encadré `Remarque` qui cite le package openxlsx comme package à privilégier pour les exports.
close #419

MAJ discours sur openxls vs read_excel pour les imports

---

03_Fiches_thematiques/Fiche_import_fichiers_plats.Rmd

Contenu de la PR :
- Suppression de la remarque sur le fait de privilégier fread() plutôt que les fonctions de {readr} en raison de la facilité de sélection des colonnes ;
- Ajout de l'argument `col_select` pour `read_csv()` et `read_csv2()` ;
- Modification des parties qui parlent de l'impossibilité de sélectionner des colonnes avec {readr} ;
- Ajout d'un paragaphe qui compare les performances d'import sur le fichier des prénoms de l'Insee par département (readr vs. data.table vs. arrow).
close #418 
Peut-être @ericemc3 pour une relecture et des compléments ?

Petite MAJ partie sur readr

---

_quarto.yml

car actuellement les boutons Edit et Source pointent sur la branche `main` (valeur par défaut dans _quarto.yml) sur le site web

quarto repo-branch:master

---

01_R_Insee/Fiche_utiliser_Rstudio_SSPCloud.qmd

Ajout de lien de la [doc en ligne du Datalab](https://datalab.sspcloud.fr/) à la page 29 (*Utiliser RStudio sur l’environnement SSP Cloud*)

add link online documentation sspcloud

---

03_Fiches_thematiques/Fiche_donnees_temporelles.qmd
DESCRIPTION
_quarto.yml

Proposition d'une nouvelle fiche sur les séries temporelles en R.

Ajout d'une nouvelle fiche sur les données temporelles (issue #491)

---

01_R_Insee/Fiche_installer_packages.qmd
02_Bonnes_pratiques/05-regles.qmd

Ajoute dans la fiche sur l'installation et l'import de packages une note sur l'utilisation de `::`.
Closes #375

Ajoute infos sur l'opérateur :: dans la fiche packages

---

01_R_Insee/presentation_utilitr.qmd

Le passage de Rmarkdown à Quarto provoque des bugs sur les codes inline. Cette PR règle un problème sur la liste des contributeurs.

Correction bug code inline

---

.github/workflows/prod.yaml

Fix quarto publishing pages

---

03_Fiches_thematiques/Fiche_import_fichiers_parquet.qmd

Je propose quelques évolutions de la fiche sur parquet pour répondre en particulier aux issues #519 et #522

proposition d'ajout sur les fichiers parquet

---

01_R_Insee/Fiche-personnaliser-R.qmd

Cette PR propose de compléter la fiche "Personnaliser la configuration de `R`"  qui incite à configurer plus largement les variables pour le proxy au niveau de l'utilisateur Windows.  
Je confirme que :

Ajout d'informations sur la configuration du proxy au niveau de l'OS

---

01_R_Insee/Fiche_utiliser_utilitR.qmd
03_Fiches_thematiques/Fiche_donnees_temporelles.qmd

PR complémentaire de l'issue InseeFrLab/utilitR#505.
Correction des 2 premiers points en R4.2.
Remarques :
- le 3ème point n'est pas corrigé
- Cette modif avait pour origine le fait que le book était construit en R 4.2 mais maintenant qu'il est construit en R4.3 (https://github.com/InseeFrLab/utilitR/blob/8c641ac3768a7a13548ab3624ac1248b371966ba/Dockerfile#L1), elle semble un peu inutile... 
Ouverture :
- Pour la suite, possibilité de :
- compléter avec un paragraphe sur le package **RJDemetra**
- compléter avec du code de v4.3 et v4.2

correction fiche données temporelle

---

03_Fiches_thematiques/Fiche_duckdb.qmd

Dans la foulée de la publication de cette superbe fiche duckdb, je propose d'ajouter un petit tableau synthétique comparant certains cas d'usage de duckdb et arrow. En l'état actuel des choses, il me semble en effet difficile pour un utilisateur débutant de savoir pourquoi utiliser l'un, l'autre ou les deux packages.
C'est une ébauche : le contenu du tableau est ouvert à discussion, pour ajouter ou retirer des items.
J'ai choisi de le mettre dans la partie introductive après "Quels sont les avantages de duckdb?" et "Quels sont les points d’attention à l’usage ?", mais je suis là aussi ouvert à la discussion.

Comparaison cas d'usage arrow et duckdb

---

03_Fiches_thematiques/Fiche_configurer_git.qmd

Il manquait un # dans un lien interne à la page pour qu'il soit fonctionnel. J'ai aussi rentré le "l'" dans le texte d'un autre lien uniquement pour des questions cosmétiques.

correction d'un lien non fonctionnel

---

03_Fiches_thematiques/Fiche_tidyverse.qmd

@linogaliana 
Petite PR pour répondre à l'issue posée par @pierre-lamarche dans #541 et qui présente rapidement les fonctions `separate_wider_delim` et `separate_wider_position` en remplacement de `separate`

Remplacement de la fonction separate désormais *superseded*
